import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import "./globals.css"

import { SidebarProvider } from "@/context/SidebarContext"
import { ThemeProvider } from "@/context/ThemeContext"
import { store } from "@/redux/store"

import { Provider } from "react-redux"

const outfit = Outfit({
	variable: "--font-outfit-sans",
	subsets: ["latin"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${outfit.variable} dark:bg-gray-900`}>
				<Provider store={store}>
					<ThemeProvider>
						<SidebarProvider>{children}</SidebarProvider>
					</ThemeProvider>
				</Provider>
			</body>
		</html>
	)
}
